# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'h2v_module.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(541, 492)
        MainWindow.setStyleSheet("background-color: #7FFF00;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(500, 100))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.file_view = QtWidgets.QLabel(self.frame)
        self.file_view.setMinimumSize(QtCore.QSize(320, 0))
        self.file_view.setStyleSheet("border: 1px solid black;\n"
"border-radius: 2.5px;\n"
"background-color: white;")
        self.file_view.setText("")
        self.file_view.setObjectName("file_view")
        self.horizontalLayout.addWidget(self.file_view)
        self.search_file = QtWidgets.QPushButton(self.frame)
        self.search_file.setStyleSheet("background-color: #D3D3D3;")
        self.search_file.setObjectName("search_file")
        self.horizontalLayout.addWidget(self.search_file)
        self.verticalLayout.addWidget(self.frame)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777196))
        self.tableWidget.setStyleSheet("background-color: white;\n"
"border: 0.5px solid black;\n"
"border-radius: 2.5px;")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.save = QtWidgets.QPushButton(self.frame_2)
        self.save.setStyleSheet("background-color: #D3D3D3;")
        self.save.setObjectName("save")
        self.horizontalLayout_2.addWidget(self.save)
        self.clear = QtWidgets.QPushButton(self.frame_2)
        self.clear.setStyleSheet("background-color: #D3D3D3;")
        self.clear.setObjectName("clear")
        self.horizontalLayout_2.addWidget(self.clear)
        self.run = QtWidgets.QPushButton(self.frame_2)
        self.run.setStyleSheet("background-color: #D3D3D3;")
        self.run.setObjectName("run")
        self.horizontalLayout_2.addWidget(self.run)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 541, 21))
        self.menubar.setObjectName("menubar")
        self.menuH2V_Module = QtWidgets.QMenu(self.menubar)
        self.menuH2V_Module.setObjectName("menuH2V_Module")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuH2V_Module.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Almacenamiento en H2V"))
        self.label_2.setText(_translate("MainWindow", "Input:"))
        self.search_file.setText(_translate("MainWindow", "Search"))
        self.save.setText(_translate("MainWindow", "Save"))
        self.clear.setText(_translate("MainWindow", "Clear"))
        self.run.setText(_translate("MainWindow", "Run"))
        self.menuH2V_Module.setTitle(_translate("MainWindow", "H2V Module"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
